"""Add Account table

Revision ID: 3828b633e769
Revises: 721de313f036
Create Date: 2024-12-17 18:24:44.977804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3828b633e769'
down_revision: Union[str, None] = '721de313f036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('fio', sa.String(), nullable=False))
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('employees', 'fio')
    # ### end Alembic commands ###
